inverted-lists/src/endpoint/models.py
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func
from typing import Optional
import datetime

from src.endpoint.extensions import db


class Document(db.Model):
    __tablename__ = 'documents'

    id: Mapped[int] = mapped_column(primary_key=True)
    src: Mapped[str] = mapped_column(index=True, unique=True)
    name: Mapped[Optional[str]]
    notes: Mapped[Optional[str]]
    is_favourite: Mapped[bool] = mapped_column(default=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        insert_default=func.now())

inverted-lists/src/endpoint/__init__.py
from flask import Flask, render_template
from random import randint
import time
import datetime

from src.endpoint.extensions import db
from src.endpoint.blueprints.home import home
from src.endpoint.blueprints.forum import forum

# To launch from shell: FLASK_APP=src.endpoint FLASK_DEBUG=on flask run


def create_app(environment_name='dev'):
    app = Flask(__name__)

    # custom config
    # app.config.from_object(configs[environment_name])

    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite+pysqlite:///data.sqlite3"
    db.init_app(app)

    with app.app_context():
        db.create_all()

    @app.errorhandler(500)
    def handle_error(exception):
        return render_template('500.html')  # pragma: no cover

    @app.template_filter()
    def format_datetime(value, format='medium'):
        if isinstance(value, datetime.datetime):
            return value.strftime("%d %b %Y at %H:%M")
        elif isinstance(value, int):
            return time.strftime("%d %b %Y at %H:%M", time.gmtime(value))

        # old formatter
        '''
        if format == 'full':
            format = "EEEE, d. MMMM y 'at' HH:mm"
        elif format == 'medium':
            format = "EE dd.MM.y HH:mm"
        # return babel.dates.format_datetime(value, format)
        # return time.strftime("%a, %d %b %Y %H:%M:%S +0000", time.gmtime(value))
        return time.strftime("%d %b %Y at %H:%M", time.gmtime(value))
        # return time.ctime(value)
        '''

    @app.template_filter()
    def forum_title(value):
        if '|' in value:
            parts = value.split('|')
            return f'{parts[0]}\n{parts[1]}'

    app.register_blueprint(home, url_prefix='/')
    app.register_blueprint(forum, url_prefix='/forum')
    return app

inverted-lists/src/endpoint/blueprints/forum.py
import base64
from flask import Blueprint, render_template, redirect, request, url_for

from src.dataset import Dataset
from src.endpoint.extensions import db
from src.endpoint.models import Document
from src.dss import System, RecordStorage
from src.private import club

from tailor import TorrentsTailor, BooksTailor, CoursesTailor
from itertools import chain
from sqlalchemy import select


forum = Blueprint('forum', __name__)


@forum.route('/', methods=['GET'])
def listing_page():
    return render_template('forum/index.html', topics=latest_forum_entries_gen())

@forum.route('/<id>', methods=['GET'])
def details(id):
    dss = System('barley', data_root='./_tmp/dss')
    forum_topics = dss.get_record_storage('forum_topics')
    topic_id_index = dss.open_id_index('forum_topics')

    record_id = topic_id_index.find(int(id))
    topic_bytes = forum_topics.find_by_id(record_id)
    topic = club.PostEntry.deserialize(topic_bytes)
    dss._cleanup()

    return render_template('forum/details.html', entry=topic)


def latest_forum_entries_gen():
    dss = System('barley', data_root='./_tmp/dss')
    forum_topics = dss.get_record_storage('forum_topics')
    topic_id_index = dss.open_id_index('forum_topics')
    sorted_by_ts = []
    for topic_id, record_id in topic_id_index.iterate():
        topic_bytes = forum_topics.find_by_id(record_id)
        topic = club.PostEntry.deserialize(topic_bytes)
        sorted_by_ts.append((topic.last_msg_timestamp, record_id))
    sorted_by_ts.sort(key=lambda u: u[0], reverse=True)
    
    # --- Listing entries with descending timestamps
    for ts, record_id in sorted_by_ts:
        topic_bytes = forum_topics.find_by_id(record_id)
        topic = club.PostEntry.deserialize(topic_bytes)
        yield topic

    dss._cleanup()

inverted-lists/src/endpoint/blueprints/home.py
import base64
from flask import Blueprint, render_template, redirect, request, url_for

from src.dataset import Dataset
from src.endpoint.extensions import db
from src.endpoint.models import Document
from tailor import TorrentsTailor, BooksTailor, CoursesTailor
from itertools import chain
from sqlalchemy import select


home = Blueprint('home', __name__)


@home.route('/', methods=['GET'])
def home_page():
    args = request.args
    q = args.get('q', default=None)

    if q is None:
        return render_template('home/index.html')
    else:
        torrents = TorrentsTailor()
        torrent_gen = torrents.search(q)
        books = BooksTailor()
        books_gen = books.search(q)
        courses = CoursesTailor()
        courses_gen = courses.search(q)

        entries = chain(
            torrent_gen,
            courses_gen,
            books_gen,
        )

        return render_template('home/index_results.html', q=q, entries=entries)


@home.route('/entry/<src>', methods=['GET'])
def details(src):
    src_decoded = base64.urlsafe_b64decode(bytes(src, 'utf-8')).decode()
    data_src, id = src_decoded.split(':')
    subdir, name = data_src.split('/')

    ds = Dataset(name, None, subdir)
    entry = ds.find_by_id(int(id))

    def get_doc():
        return db.session.execute(
            db.select(Document).where(Document.src == src_decoded)).scalar()
        # db.select(Document).where(Document.src == src_decoded)).scalar_one()
        # select(Document)).first()

    db_doc = get_doc()
    if db_doc is None:
        db_doc = Document(
            src=src_decoded,
            name=entry['name'],
        )
        db.session.add(db_doc)
        db.session.commit()
        db_doc = get_doc()

    print('- doc 0', db_doc.__dict__)

    return render_template('home/details.html', entry=entry, db_doc=db_doc)


@home.route('/entry/<src>', methods=['POST'])
def details_update(src):
    src_decoded = base64.urlsafe_b64decode(bytes(src, 'utf-8')).decode()
    # doc = db.get_or_404(Document, id)
    doc = db.session.execute(
        db.select(Document).where(Document.src == src_decoded)).scalar_one()
    if doc is not None:
        notes = request.form.get('notes', None)
        is_fav = request.form.get('is_favourite', 'off')
        is_fav = True if is_fav == 'on' else False

        doc.notes = notes
        doc.is_favourite = is_fav
        db.session.commit()
    return redirect(url_for('home.details', src=src))


@home.route('/favourites')
def favourites():
    docs = db.session.execute(
        db.select(Document).where(Document.is_favourite == True)).scalars()
    return render_template('home/favourites.html', docs=docs)


@home.route('/recents')
def recents():
    return render_template('home/recents.html')


@home.route('/about')
def about():
    return render_template('home/about.html')

inverted-lists/src/endpoint/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}HLibrary{% endblock %} • HL</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a href="{{ url_for('home.home_page') }}" class="navbar-brand">HL</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if request.url_rule.endpoint == 'home.home_page'%}active{% endif %}"
              aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.url_rule.endpoint == 'home.recents'%}active{% endif %}"
              href="/recents">Recents</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.url_rule.endpoint == 'home.favourites'%}active{% endif %}"
              href="/favourites">Favourites</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.url_rule.endpoint == 'home.favourites'%}active{% endif %}"
              href="/forum">Forum</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.url_rule.endpoint == 'home.about'%}active{% endif %}"
              href="/about">About</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container mt-4">
      {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"></script>
  </body>

</html>

inverted-lists/src/endpoint/templates/forum/details.html
{% extends "base_layout.html" %}
{% block title %}Details{% endblock %}

{% block content %}

<h3>Details</h3>
<ul class="mb-5 w-50 list-group">
  <li class="list-group-item">
    <a href="{{entry.url}}"
      class="link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-75-hover text-nowrap text-primary fs-6 fw-light">{{entry.id}}</a>
  </li>
  <li class="list-group-item">{{entry.title}}</li>
  <li class="list-group-item">size: {{entry.size}}</li>
  <li class="list-group-item">{{entry.views}} / {{entry.answers}} - {{entry.last_message_dt | format_datetime}}</li>
  <li class="list-group-item">{{entry.seeders}}/{{entry.leechers}}</li>
  <li class="list-group-item">{{entry.description}}</li>
</ul>

{% endblock %}

inverted-lists/src/endpoint/templates/forum/index.html
{% extends "base_layout.html" %}
{% block title %}Home{% endblock %}

{% block content %}

<h1>Recent forum entries</h1>
<p>Simple way to find what you need.</p>

{% for topic in topics %}
<div class="my-3">
  <a href="{{ url_for('forum.details', id=topic.id ) }}"
    class="link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-75-hover text-nowrap text-primary fs-6 fw-light">{{topic.title | forum_title}}</a>
  <div class="text-secondary fw-medium" style="font-size:11px;">
    <span class="pe-3">{{topic.last_message_dt|format_datetime}}</span>
  </div>
</div>
{% endfor %}

{% endblock %}

inverted-lists/src/endpoint/templates/home/_form.html
<div class="d-flex flex-column align-items-center">
  <h4>HLibrary</h4>

  <form action="/" method="GET" class="w-50">
    <div class="input-group">
      <input type="text" class="form-control" name="q" placeholder="" value="{{ q }}">
      <button class="px-5 btn btn-secondary" type="button">Go</button>
    </div>
  </form>
  <p class="text-secondary" style="font-size: 11px">This is a quick way to find what you need.</p>

</div>

inverted-lists/src/endpoint/templates/home/about.html
{% extends "base_layout.html" %}
{% block title %}Home{% endblock %}

{% block content %}

<h1>Welcome to HLibrary</h1>
<p>Simple way to find what you need.</p>

{% endblock %}

inverted-lists/src/endpoint/templates/home/details.html
{% extends "base_layout.html" %}
{% block title %}Details{% endblock %}

{% block content %}

<h3>Details</h3>
<ul class="mb-5 w-50 list-group">
  <li class="list-group-item">Id: {{entry.src}}</li>
  <li class="list-group-item">Name: {{entry.name}}</li>
  <li class="list-group-item">Path: {{entry.path}}</li>
  <li class="list-group-item">Comment: {{entry.comment}}</li>
  <li class="list-group-item">Size: {{entry.size | filesizeformat}}</li>
  <li class="list-group-item">Created: {{entry.created | format_datetime }}</li>
  <li class="list-group-item">Upserted: {{db_doc.created_at | format_datetime }}</li>
</ul>

<form action="" method="post" class="w-50">
  <div class="mb-3">
    <label for="nameField" class="form-label">Name</label>
    <input type="text" class="form-control" id="nameField" aria-describedby="nameFieldHelp"
      value="{{db_doc.name or ''}}">
    <div id="nameFieldHelp" class="form-text">Managed separately from the original name.</div>
  </div>
  <div class="mb-1">
    <label for="notesInput" class="form-label">Notes</label>
    <textarea name="notes" id="notesInput" class="form-control" cols="30" rows="3">{{db_doc.notes or ''}}</textarea>
  </div>
  <div class="mb-4 form-check">
    <input class="form-check-input" type="checkbox" name="is_favourite" id="favouriteCheck" {{'checked' if
      db_doc.is_favourite else '' }}>
    <label class="form-check-label" for="favouriteCheck">
      Favourite
    </label>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

inverted-lists/src/endpoint/templates/home/favourites.html
{% extends "base_layout.html" %}
{% block title %}Details{% endblock %}

{% block content %}

<h3>Favourites</h3>
{% for entry in docs %}
<div class="my-3">
  <div class="text-secondary fw-light" style="font-size:12px;">{{entry.name}}</div>
</div>
{% endfor %}

{% endblock %}

inverted-lists/src/endpoint/templates/home/index.html
{% extends "base_layout.html" %}
{% block title %}Home{% endblock %}

{% block content %}
{% include 'home/_form.html' %}
{% endblock %}

inverted-lists/src/endpoint/templates/home/index_results.html
{% extends "base_layout.html" %}
{% block title %}Home{% endblock %}

{% block content %}

{% include 'home/_form.html' %}

{% if entries %}
<div class="my-3">
  {% for entry in entries %}
  <div class="my-3">
    <a href="{{ url_for('home.details', src=entry.src ) }}"
      class="link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-75-hover text-nowrap text-primary fs-5 fw-light">{{entry['name']}}</a>
    <div class="text-secondary fw-medium" style="font-size:11px;">
      <span class="pe-3">{{entry['created']|format_datetime}}</span>
      <span class="">{{entry['size']|filesizeformat}}</span>
    </div>
    <div class="text-secondary fw-light" style="font-size:12px;">{{entry['path']}}</div>
  </div>
  {% endfor %}
  {% else %}
  <p>No results found</p>
</div>
{% endif %}

{% endblock %}

inverted-lists/src/endpoint/templates/home/recents.html
{% extends "base_layout.html" %}
{% block title %}Details{% endblock %}

{% block content %}

<h3>Recents</h3>

{% endblock %}